
const DEBUG = false;

const RELEASE = true;

export default {
  MEASURE_SOLVING_TIMEOUT: 60,

  DEBUG_GREEDY: true,

  SHOW2D_SAMPLE_COUNT: 500,

  SHOW2D_TREE_FULL: false,
  SHOW2D_TREE_PART: DEBUG,

  SHOW2D_AGENT: RELEASE,
  SHOW2D_AGENT_SHADOW: RELEASE,
  SHOW2D_SAMPLES: RELEASE,
  SHOW2D_WALLS: true,

  SHOW3D_TREE_PART: DEBUG,
  SHOW3D_SOLUTION_KEYFRAME_COUNT: 5,

  FRAME_TIME: 50
};